language: rust
rust:
- stable
- beta
- nightly
sudo: false
env:
  secure: "j+2pQ6bPyZzTWuk47A9cw5/w+UvCretUZ/Tn3pUtscjFUFuMqLhJpUoyD3kcVx5bmgXFYhCZFiHuMozixi/MXtET3hXsfIpTOxu15BpFlGUcuFqzZMnDoTtQuijEnPK8LAfsUH+dMujRf9UN1WNHewiHFax7FJcnmi5tC3RVf8szwa6YIcPLr6uywD2QbpLzphy97OXb6HAdKJnOBmvrPrin8/6OUtIUkfhnA1wd0itKZBO07ooGRPAs3Wes8v4hLi3zhtWOXWcWF/byvfdzbk9kYFBcdGLDtJQ8T+rh7KMBiPmK3m5kgPKJODqHiWWU0Y+d8rl1tjwsUWzb2nwpXP/tJTjURKL+Uz8YsCly5agsF5mDWM0t8SawYdCCQdupsJBc5FET6mo8IdErxKjqZzsRgzw6lwLvjuygkghJcRpmvtplatHpon6jYK7N9GsEi4A42bSk1OdWtl82KHr1DUv2sQk+znZzBU5tYv52vMjyBeeNqHgt22UCLg2aNyn1QIOI2tCfAizLIVVP7LkfJd44WA/9BLEZgQdo/QckEM5dHSJOAO3hTiBAvsCtgoM6pXatJ79GhCNRw3bEufiz0O2lDzXxOKsejXnqS9kBWCkuvjoRHwwffX1qVGJ+DUo4/Rhioukh+64EP1bPUySzhwkZIZGCBbZWKBkmT/K9dA0="
script:
- cargo build --verbose
- cargo test --verbose
after_success: |
  [ $TRAVIS_RUST_VERSION = stable ] &&
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2 | tr '-' '_'`/index.html>" > target/doc/index.html &&
  pip install ghp-import --user &&
  ~/.local/bin/ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
